/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;


class AppTest
{
    @Test void test_appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app App classUnderTest = new App();should have a greeting");
    }

    @DisplayName("default test")
    @Test void test_RandomQuote() throws IOException {
        App sut= new App();
        String path = "../app/src/test/resources/recentquotes.json";
        String quote = "{\"quoteAuthor\": Marilyn Monroe\n" +
                "\"quoteText\": I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.\"\n" +
                "}";
        System.out.println("hello");
        assertEquals(sut.randomQuote(path, true), quote, "Error Message: default test");
    }





}
