/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        
        getJsonData();
    }

    public static void getJsonData() throws IOException {
        String path = "C:\\Users\\trega\\codefellows\\401\\java\\quotes\\quotes\\app\\src\\test\\resources" +
                "\\recentquotes.json";
        System.out.println(randomQuote(path, true));
    }

    public static String randomQuote(String path, Boolean test) throws IOException {


        File file = new File(path); // input file path
        FileReader readFileLines = new FileReader(file); // read file
        Gson gson = new Gson(); // create a new gson object- this will be used to convert Java Object to JSON
        // representation

        Quotes[] json = gson.fromJson(readFileLines, Quotes[].class); // serialize data
        int index;
        if (test.equals(true)) { // checking input boolean: this will change our index variable
            index = 0;
        } else {
            index = (int) (Math.random() * json.length);
        } // get random number for our json array index
        String author = json[index].author + ": "; // extract author's name at randomly generated index
        String text = "\"" + json[index].text + "\"" ; // extract text at randomly generated index
        return author + text; // return author + text in String format
    }
}
